// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: links.sql

package sqlcgen

import (
	"context"
)

const createLink = `-- name: CreateLink :one
INSERT INTO links (original_url, shortcode)
VALUES ($1, $2)
RETURNING
    id, original_url, shortcode
`

type CreateLinkParams struct {
	OriginalUrl string `json:"original_url"`
	Shortcode   string `json:"shortcode"`
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error) {
	row := q.db.QueryRowContext(ctx, createLink, arg.OriginalUrl, arg.Shortcode)
	var i Link
	err := row.Scan(&i.ID, &i.OriginalUrl, &i.Shortcode)
	return i, err
}

const deleteLink = `-- name: DeleteLink :execrows
DELETE FROM links
WHERE id = $1
`

func (q *Queries) DeleteLink(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteLink, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getLinkByCode = `-- name: GetLinkByCode :one
SELECT
    id, original_url, shortcode
FROM links
WHERE shortcode = $1
`

func (q *Queries) GetLinkByCode(ctx context.Context, shortcode string) (Link, error) {
	row := q.db.QueryRowContext(ctx, getLinkByCode, shortcode)
	var i Link
	err := row.Scan(&i.ID, &i.OriginalUrl, &i.Shortcode)
	return i, err
}

const getLinkByID = `-- name: GetLinkByID :one
SELECT
    id, original_url, shortcode
FROM links
WHERE id = $1
`

func (q *Queries) GetLinkByID(ctx context.Context, id int64) (Link, error) {
	row := q.db.QueryRowContext(ctx, getLinkByID, id)
	var i Link
	err := row.Scan(&i.ID, &i.OriginalUrl, &i.Shortcode)
	return i, err
}

const getLinks = `-- name: GetLinks :many
SELECT
    id, original_url, shortcode
FROM links
LIMIT $1 OFFSET $2
`

type GetLinksParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetLinks(ctx context.Context, arg GetLinksParams) ([]Link, error) {
	rows, err := q.db.QueryContext(ctx, getLinks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Link
	for rows.Next() {
		var i Link
		if err := rows.Scan(&i.ID, &i.OriginalUrl, &i.Shortcode); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLinksTotalCount = `-- name: GetLinksTotalCount :one
SELECT count(*) as total
FROM links
`

func (q *Queries) GetLinksTotalCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getLinksTotalCount)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const updateLink = `-- name: UpdateLink :one
UPDATE links
SET
    original_url = $2,
    shortcode = $3
WHERE id = $1
RETURNING
    id, original_url, shortcode
`

type UpdateLinkParams struct {
	ID          int64  `json:"id"`
	OriginalUrl string `json:"original_url"`
	Shortcode   string `json:"shortcode"`
}

func (q *Queries) UpdateLink(ctx context.Context, arg UpdateLinkParams) (Link, error) {
	row := q.db.QueryRowContext(ctx, updateLink, arg.ID, arg.OriginalUrl, arg.Shortcode)
	var i Link
	err := row.Scan(&i.ID, &i.OriginalUrl, &i.Shortcode)
	return i, err
}
