// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

type Link struct {
	ID          int64  `json:"id"`
	OriginalUrl string `json:"original_url"`
	Shortcode   string `json:"shortcode"`
}
