// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
)

type Querier interface {
	CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error)
	CreateVisit(ctx context.Context, arg CreateVisitParams) (int64, error)
	DeleteLink(ctx context.Context, id int64) (int64, error)
	GetLinkByCode(ctx context.Context, shortcode string) (Link, error)
	GetLinkByID(ctx context.Context, id int64) (Link, error)
	GetLinksTotalCount(ctx context.Context) (int64, error)
	GetVisitsTotalCount(ctx context.Context) (int64, error)
	UpdateLink(ctx context.Context, arg UpdateLinkParams) (Link, error)
}

var _ Querier = (*Queries)(nil)
