// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: visits.sql

package sqlcgen

import (
	"context"
	"database/sql"

	"github.com/sqlc-dev/pqtype"
)

const createVisit = `-- name: CreateVisit :execrows
INSERT INTO visits
    (link_id, ip, referer, user_agent, status)
VALUES
    ($1, $2, $3, $4, $5)
`

type CreateVisitParams struct {
	LinkID    int64          `json:"link_id"`
	Ip        pqtype.Inet    `json:"ip"`
	Referer   sql.NullString `json:"referer"`
	UserAgent sql.NullString `json:"user_agent"`
	Status    int16          `json:"status"`
}

func (q *Queries) CreateVisit(ctx context.Context, arg CreateVisitParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createVisit,
		arg.LinkID,
		arg.Ip,
		arg.Referer,
		arg.UserAgent,
		arg.Status,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getVisitsTotalCount = `-- name: GetVisitsTotalCount :one
SELECT count(*)
FROM visits
`

func (q *Queries) GetVisitsTotalCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getVisitsTotalCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}
