// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: visits.sql

package sqlcgen

import (
	"context"
)

const getVisitsTotalCount = `-- name: GetVisitsTotalCount :one
SELECT count(*)
FROM visits
`

func (q *Queries) GetVisitsTotalCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getVisitsTotalCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}
